### ISSUE TITLE
Expand FDataDict usage

### ISSUE THREAD

**Issue by ndinsmore** [PetrKryslUCSD/FinEtoolsDeforLinear.jl#2]
Coming from an Ansys background I am very used to having everything stored in the "database".

That makes me think that a lot more data could be stored in the FDataDict?   
I could do this outside of the module but if you were open to expanded capability I would happily build that functionality in a way that could be pulled into the module.

Update: Looking more detailed I see that a lot of this is already done.  I was thrown for a loop because the modifying methods don't include a ! in the names.

I think that one of the areas that could be helpful is making some of the interm steps modify the FDataDict as well.    For example, I am working on a multilateral dynamics problem where I need the mass and stiffness matrices.   That is certainly done already in the modal method but would be great to expose that as well.

**Comment by PetrKryslUCSD** [comment]
Sorry, I totally missed this comment. My apologies!

You are right, that data dictionary could be used for carrying around model data and results. It already does that to a large degree. Let us talk about what it is you'd like to accomplish.
